export const homeCategories = [
  {
    id: 1,
    name: "Home Decor",
    slug: "home-decor",
    dbQueryValue: "Home Decor",
    linkUrl: "/home-decor",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1779767408/Gemini_Generated_Image_5qyggl5qyggl5qyg_xylpz5.png",
    gridClass: "md:col-span-2",
  },
  {
    id: 2,
    name: "Lamps & Lighting",
    slug: "lamps-lighting",
    dbQueryValue: "Lamps & Lighting",
    linkUrl: "/lamps-lighting",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1778816792/pexels-i-brahim-serdar-609612458-18189836_hxlvv5.jpg",
    gridClass: "md:col-span-1",
  },
  {
    id: 3,
    name: "Basket & Storage",
    slug: "basket-storage",
    dbQueryValue: "Baskets & Storage",
    linkUrl: "/basket-storage",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1779769617/wicker-baskets_qblrgw.jpg",
    gridClass: "md:col-span-1",
  },
  {
    id: 4,
    name: "Birds Nest",
    slug: "birds-nest",
    dbQueryValue: "Birds Nest",
    linkUrl: "/birds-nest",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1778816666/pexels-litoon-dev-148552401-36879495_kl2x66.jpg",
    gridClass: "md:col-span-2",
  },
  {
    id: 5,
    name: "Gifts & Crafts",
    slug: "gifts-crafts",
    dbQueryValue: "Gifts & Crafts",
    linkUrl: "/gifts-crafts",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1778816750/pexels-alex-souza-763919741-29528053_d0uwxa.jpg",
    gridClass: "md:col-span-1",
  },
  {
    id: 6,
    name: "Wall Decor",
    slug: "wall-decor",
    dbQueryValue: "Wall Decor",
    linkUrl: "/wall-decor",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1778816701/pexels-eslames1-31538813_xhzyrx.jpg",
    gridClass: "md:col-span-1",
  },
  {
    id: 7,
    name: "Fashion Accessories",
    slug: "fashion-accessories",
    dbQueryValue: "Fashion Accessories",
    linkUrl: "/fashion-accessories",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1778816753/pexels-ali-can-demi-r-686670066-19392702_enog50.jpg",
    gridClass: "md:col-span-1",
  },
  {
    id: 8,
    name: "Others",
    slug: "others",
    dbQueryValue: "Others",
    linkUrl: "/others",
    imageUrl: "https://res.cloudinary.com/dlm5fnpnv/image/upload/v1779769787/tropical-green-bamboo-forest_ehwxvg.jpg",
    gridClass: "md:col-span-3",
  },
];